---
title: "HW_05_IPA"
author: "Gantungalag"
date: "5/27/2020"
output: html_document
---

```{r}
rm(list=ls())


#1. Download 10 industry portfolio returns (average value-weighted monthly returns) from Fama  French data library (http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html)
# library(readr)
Data <- read.csv("Data.csv")
head(Data)
```


```{r}
#2. Compute equal weight portfolio returns EACH month starting from 2000/01 to 2020/03. 
#   Denote this strategy as the Benchmark portfolio and create its backtesting report using SIT. 
nrow(Data)
con = gzcon(url('https://github.com/systematicinvestor/SIT/raw/master/sit.gz', 'rb'))
source(con)
close(con)
# install.packages(rlang)
#install.packages(pacman)
library(pacman)
library(xts)
#install.packages(xts)
p_load(quantmod, quadprog, lpSolve)

```


```{r}
date <- seq(as.Date("1926-08-01"), length=1125, by="1 month") -1
Data <- xts(coredata(Data[, -1])/100, order.by = date)
head(Data)
Data.price <- cumprod(Data + 1) *100
head(Data.price)
Data.1 <- Data.price['199912/202003']
head(Data.1)
```

```{r}
#to create equal weight
#we need 5 inputs :

data <- new.env()
data$prices <- Data.1
data$weight <- Data.1
data$execution.price <- data$prices
data$execution.price[] <- NA
data$symbolnames <- colnames(data$prices)

prices <- data$prices
n <-  ncol(prices)
data$weight <- ntop(prices, n)

```

```{r}
#method 1
model <- list()
model$equal.weight <- bt.run(data, trade.summary = T)
#method 2
capital = 100000
data$weight[] = (capital / prices) * data$weight
equal.weight = bt.run(data, type='share')
head(equal.weight$ret)
```

```{r}
bt.detail.summary(model$equal.weight)
plotbt.monthly.table(model$equal.weight$equity)
plotbt.transition.map(model$equal.weight$weight)
strategy.performance.snapshoot(model, T)

```

```{r}
#3. Compute  MVP portfolio returns by rebalancing EACH month starting from 2000/01 to 2020/03. 
#Use in-sample data range of 36 months to compute covariance matrix. 
#Denote this strategy as the MVP portfolio and create its backtesting report using SIT.
prices.2 <- Data.price["199701/202003"]
head(prices.2)
tail(prices.2)

data$prices <- prices.2
data$weight <- prices.2
data$execution.price <-prices.2 * NA

prices.3 <- data$prices

```

```{r}
# Create Constraints
#*****************************************************************
constraints = new.constraints(n, lb = -Inf, ub = +Inf)

# SUM x.i = 1
constraints = add.constraints(rep(1, n), 1, type = '=', constraints)        

ret = prices.3 / mlag(prices) - 1
weight = coredata(prices.3)
weight[] = NA
nrow(prices.3)

hist <- na.omit(ret[1:36,])
cov(hist)
ia = create.historical.ia(hist,12)
s0 = apply(coredata(hist), 2 , sd)
ia$cov = cor(coredata(hist), use='complete.obs',method='pearson') * (s0 %*% t(s0))
weight[36,] = min.risk.portfolio(ia, constraints)
weight[36,]
sum(weight[36,])
```


```{r}
model$min.var.monthly <- bt.run(data, trade.summary = T)
#data$weight[] = weight     
#capital = 100000
#data$weight[] = (capital / prices) * data$weight

# to verify the default do.lag  = 1 day
sum(as.numeric(weight[36,])*as.numeric(ret[37,]))
model$min.var.monthly$ret[37, ]

```


```{r}
#4. Plot both strategies side by side and compare their performance and comment.
#Publish your results in RPubs and upload your link.

plotbt.custom.report.part1(model$min.var.monthly, model$equal.weight)
#
layout(1:2)
plotbt.transition.map(model$min.var.monthly$weight)
legend('topright', legend = 'min.var.monthly', bty = 'n')
plotbt.transition.map(model$equal.weight$weight)
legend('topright', legend = 'equal weight', bty = 'n')

strategy.performance.snapshoot(model, T)
model <- rev(model)
plotbt.custom.report(model)

```


```{r}

```
```{r}

```
```{r}

```
